services:
  postgresql:
    image: "bitnami/postgresql:16"
    container_name: bdr-postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/bitnami/postgresql 
      - ./db:/docker-entrypoint-initdb.d
      - ../dataAdresse:/dataAdresse
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse_proxy:
    image: traefik
    command:
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/ssl:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
    ports:
      - "80:80" # Web sites
      - "443:443" # Web sites
      - "8080:8080" # Traefik dashboard

  backend:
    build:
      context: ../../Gestion-Decheterie-Backend/backend
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.backend.rule=Host(`localhost`) &&
        PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.tls=true
      - traefik.http.services.backend.loadbalancer.sticky=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.name=StickyCookie
      - traefik.http.services.backend.loadbalancer.sticky.cookie.secure=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.samesite=strict
    deploy:
      replicas: 1
    environment:
      - BACKEND_APP_API_URL=${BACKEND_APP_API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SEQUELIZE_LOGS=${SEQUELIZE_LOGS}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      postgresql:
        condition: service_healthy

  frontend:
    build:
      context: ../../Gestion-Decheterie-Frontend/frontend
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls=true
    deploy:
      replicas: 1
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

volumes:
  pg_data:
