
services:
  postgresql:
    image: "bitnami/postgresql:16"
    container_name: bdr-postgresql
    restart: always
    environment:
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - pg_data:/bitnami/postgresql 
      - ./db:/docker-entrypoint-initdb.d
      - ../dataAdresse:/dataAdresse
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bdr"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse_proxy:
    image: traefik
    restart: always
    command:
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/ssl:/etc/traefik/certificates
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
    ports:
      - "80:80" # Web sites
      - "443:443" # Web sites
      - "8080:8080" # Traefik dashboard

  backend:
    image: justinferrara968/gestion-decheterie-backend:main
    restart: always
    labels:
      - traefik.http.routers.backend.rule=Host(`gestion-decheterie.internet-box.ch`) &&
        PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.tls=true
      - traefik.http.services.backend.loadbalancer.sticky=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.name=StickyCookie
      - traefik.http.services.backend.loadbalancer.sticky.cookie.secure=true
      - traefik.http.services.backend.loadbalancer.sticky.cookie.samesite=strict
    deploy:
      replicas: 1
    environment:
      - BACKEND_APP_API_URL=https://gestion-decheterie.internet-box.ch
      - DATABASE_URL=postgres://bdr:bdr@postgresql:5432/bdr
      - SEQUELIZE_LOGS=false
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      postgresql:
        condition: service_healthy

  frontend:
    image: justinferrara968/gestion-decheterie-frontend:main
    restart: always
    labels:
      - traefik.http.routers.frontend.rule=Host(`gestion-decheterie.internet-box.ch`)
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls=true
    deploy:
      replicas: 1
    environment:
      - REACT_APP_API_URL=https://gestion-decheterie.internet-box.ch

volumes:
  pg_data: